[build-system]
requires = ["setuptools>=80", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "magnetron-models"
version = "0.1.0"
description = "Training and Inference (Qwen3, more to come) using the Magnetron ML framework."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "huggingface-hub>=1.20.1",
    "magnetron>=0.2.0",
    "rich>=15.0.0",
    "tokenizers>=0.23.1",
]

[project.optional-dependencies]
conversion = [
    "safetensors",
    "torch",
    "ruff",
]

[project.scripts]
inference = "magnetron_models.main:main"
convert-qwen3 = "dataset_conversion_pipelines.convert_qwen3:main"
convert-qwen3-5 = "dataset_conversion_pipelines.convert_qwen3_5:main"
convert-qwen3-5-moe = "dataset_conversion_pipelines.convert_qwen3_5_moe:main"

[tool.setuptools]
packages = { find = { include = ["magnetron_models*", "dataset_conversion_pipelines*"] } }

[tool.ruff]
line-length = 150
exclude = [
    ".venv",
    "docs",
    "extern",
    "test",
    "tests",
    "tools",
    "fuzzer",
    "cmake",
    "bin",
]

[tool.ruff.lint]
ignore = ["F403"]
select = [
    "ANN",
    "UP",
]

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint.per-file-ignores]
"setup.py" = ["ANN"]
